# Linting tools configuration

[tool.ruff]
target-version = "py310"
line-length = 99
extend-exclude = [ "*.egg_info", "__pycache__" ]

lint.select = [
  "C",
  "D",
  "E",
  "F",
  "F401",
  "I",
  "I001",
  "N",
  "RUF",
  "UP",
  "W",
]
lint.ignore = [ "D107", "E501" ]
lint.extend-ignore = [
  "D203",
  "D204",
  "D213",
  "D215",
  "D400",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
]
lint.per-file-ignores = { "tests/*" = [ "D100", "D101", "D102", "D103", "D104" ] }
lint.mccabe.max-complexity = 10

[tool.codespell]
skip = "build,lib,venv,icon.svg,.tox,.git,.mypy_cache,.ruff_cache,.coverage"

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"

# Formatting tools configuration

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pyright]
include = [ "src/**.py" ]
