# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
requires =
    tox>=4.16
    tox-uv
env_list =
    format
    lint
    unit
    static
    coverage-report
    scenario
no_package = true
skip_missing_interpreters = true

[testenv]
pass_env =
    CHARM_BUILD_DIR
    MODEL_SETTINGS
    PYTHONPATH
set_env =
    PYTHONBREAKPOINT = pdb.set_trace
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PY_COLORS = 1

[testenv:format]
description = Apply coding style standards to code
deps =
    pyproject-fmt
    ruff
    toml-fmt-common<1.3.3
    tox-ini-fmt
commands =
    ruff format {[vars]all_path}
    ruff check --fix {[vars]all_path}
    - pyproject-fmt pyproject.toml
    - tox-ini-fmt tox.ini

[testenv:lint]
runner = uv-venv-lock-runner
description = Check code against coding style standards
commands =
    codespell {tox_root}
    ruff check {[vars]all_path}
    pyproject-fmt --check pyproject.toml
dependency_groups =
    lint
    scenario
    integration

[testenv:unit]
runner = uv-venv-lock-runner
description = Run unit tests
commands =
    coverage run --source={[vars]src_path} \
      -m pytest \
      --tb native \
      -v \
      -s \
      {posargs} \
      {[vars]tests_path}/unit
dependency_groups =
    unit

[testenv:static]
runner = uv-venv-lock-runner
description = Run static analysis checks
commands =
    pyright {[vars]src_path}
dependency_groups =
    lint

[testenv:coverage-report]
runner = uv-venv-lock-runner
description = Report test coverage
commands =
    coverage report
dependency_groups =
    unit

[testenv:scenario]
runner = uv-venv-lock-runner
description = Run scenario tests
commands =
    pytest -v -s --tb native {posargs} --log-cli-level=INFO {[vars]tests_path}/scenario
dependency_groups =
    scenario

[testenv:integration]
runner = uv-venv-lock-runner
description = Run integration tests
commands =
    pytest -v \
      -s \
      --tb native \
      --log-cli-level=INFO \
      {posargs} \
      {[vars]tests_path}/integration
dependency_groups =
    integration

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}
