name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/*

jobs:
  pull-request-region:
    name: PR Region
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@c8b90c2e6dea32e59a5deb089c3e76565bdee8b3 # Branch v0
    permissions:
      security-events: write
      actions: read
      contents: write
      issues: write
    secrets: inherit
    with:
      charm-path: maas-region
      juju-channel: 3.6/stable
      python-version: "3.14"
      provider: lxd
      charmcraft-channel: latest/stable
      check-library-labels: false
