name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/*

jobs:
  pull-request-region:
    name: PR Region
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@3414ea10e5fd0c10246c07937a3f621ff54cadc2 # Branch v0
    permissions:
      security-events: write
      actions: read
      contents: write
      issues: write
    secrets: inherit
    with:
      charm-path: maas-region
      juju-channel: 3.6/stable
      python-version: "3.10"
      provider: lxd
      charmcraft-channel: latest/stable
      check-library-labels: false
