name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/*

jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/operator-workflows/.github/workflows/test.yaml@4e1f0ab968d84de47fe6cf179d8fce7256f7494f # main as of 2026-07-01
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    with:
      working-directory: maas-region
      with-uv: true
      require-check-lib: false
      python-version: "3.14"

  integration-tests:
    name: Integration Tests
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@4e1f0ab968d84de47fe6cf179d8fce7256f7494f # main as of 2026-07-01
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      working-directory: maas-region
      provider: lxd
      juju-channel: 3.6/stable
      with-uv: true
      charmcraft-channel: latest/stable
      python-version: "3.14"
