name: Release Charms to Edge and Publish Libraries

on:
  push:
    branches:
      - main
      - track/*
    paths:
      - maas-region/**

jobs:
  release-region:
    name: Release MAAS Region charm to edge
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@4e1f0ab968d84de47fe6cf179d8fce7256f7494f # main as of 2026-07-01
    permissions:
      contents: write
      actions: read
    secrets: inherit
    with:
      working-directory: maas-region
      channel: latest/edge
      tag-prefix: maas-region
