name: Auto-update Charm Libraries

on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-lib-region:
    name: Check libraries
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@4e1f0ab968d84de47fe6cf179d8fce7256f7494f # main as of 2026-07-01
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    secrets: inherit
    with:
      working-directory: maas-region
